steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - >-
        --destination=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - '--cache=true'
      - '--cache-ttl=24h'
      - '--dockerfile=Dockerfile-backend'
    id: Build
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
options: {}
substitutions:
  _LABELS: gcb-trigger-id=93419193-4ad9-479d-b3b2-9f4e29a07287
  _TRIGGER_ID: 93419193-4ad9-479d-b3b2-9f4e29a07287
  _GCR_HOSTNAME: eu.gcr.io
  _PLATFORM: managed
  _SERVICE_NAME: misteryemployer-backend
  _DEPLOY_REGION: europe-west1
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - misteryemployer-backend
